# spring
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/base_api?useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Tokyo&useSSL=false
    username: rabiloo
    password: rabiloo
    hiraki:
      maximumPoolSize: 50
      maxLifetime: 420000 # 7p
      leakDetectionThreshold: 5000 # 5s
      connectionTestQuery: SELECT 1
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        min-idle: 1
        max-active: 50
        max-idle: 50
        max-wait: 10000
    timeout: 10000
  data:
    redis:
      repositories:
        enabled: false
  # liquibase (drop-first default value = false)
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/db-changelog-master.xml
    drop-first: false
  jpa:
    properties:
      hibernate:
        open-in-view: false # disable this anti pattern
        enable_lazy_load_no_trans: false # disable this anti pattern
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  jackson:
    date-format: yyyy/MM/dd HH:mm
    time-zone: Asia/Tokyo
  main:
    allow-bean-definition-overriding: true
  mail:
    host:
    username:
    password:
    properties:
      mail.smtp.starttls.enable: true
    port: 587

# Email
email:
  receiver:
server:
  servlet:
    session:
      timeout: 1d
  port: 8080

url-admin-ui: http://localhost:8083